// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/sewaustav/CaseGoCore/internal/cases/models"
	mock "github.com/stretchr/testify/mock"
)

// CaseRepo is an autogenerated mock type for the CaseRepo type
type CaseRepo struct {
	mock.Mock
}

// CreateCase provides a mock function with given fields: ctx, caseCopy
func (_m *CaseRepo) CreateCase(ctx context.Context, caseCopy *models.Case) (*models.Case, error) {
	ret := _m.Called(ctx, caseCopy)

	if len(ret) == 0 {
		panic("no return value specified for CreateCase")
	}

	var r0 *models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Case) (*models.Case, error)); ok {
		return rf(ctx, caseCopy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Case) *models.Case); ok {
		r0 = rf(ctx, caseCopy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Case) error); ok {
		r1 = rf(ctx, caseCopy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCase provides a mock function with given fields: ctx, caseID
func (_m *CaseRepo) DeleteCase(ctx context.Context, caseID int64) error {
	ret := _m.Called(ctx, caseID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCase")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, caseID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCaseByID provides a mock function with given fields: ctx, caseID
func (_m *CaseRepo) GetCaseByID(ctx context.Context, caseID int64) (*models.Case, error) {
	ret := _m.Called(ctx, caseID)

	if len(ret) == 0 {
		panic("no return value specified for GetCaseByID")
	}

	var r0 *models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Case, error)); ok {
		return rf(ctx, caseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Case); ok {
		r0 = rf(ctx, caseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, caseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCases provides a mock function with given fields: ctx, limit, offset
func (_m *CaseRepo) GetCases(ctx context.Context, limit int, offset int) ([]models.Case, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetCases")
	}

	var r0 []models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.Case, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.Case); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCasesByCategory provides a mock function with given fields: ctx, categoryID, limit, offset
func (_m *CaseRepo) GetCasesByCategory(ctx context.Context, categoryID int32, limit int, offset int) ([]models.Case, error) {
	ret := _m.Called(ctx, categoryID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetCasesByCategory")
	}

	var r0 []models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, int, int) ([]models.Case, error)); ok {
		return rf(ctx, categoryID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, int, int) []models.Case); ok {
		r0 = rf(ctx, categoryID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, int, int) error); ok {
		r1 = rf(ctx, categoryID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCasesByTopic provides a mock function with given fields: ctx, topicID, limit, offset
func (_m *CaseRepo) GetCasesByTopic(ctx context.Context, topicID string, limit int, offset int) ([]models.Case, error) {
	ret := _m.Called(ctx, topicID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetCasesByTopic")
	}

	var r0 []models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]models.Case, error)); ok {
		return rf(ctx, topicID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []models.Case); ok {
		r0 = rf(ctx, topicID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, topicID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchCase provides a mock function with given fields: ctx, caseCopy
func (_m *CaseRepo) PatchCase(ctx context.Context, caseCopy *models.Case) (*models.Case, error) {
	ret := _m.Called(ctx, caseCopy)

	if len(ret) == 0 {
		panic("no return value specified for PatchCase")
	}

	var r0 *models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Case) (*models.Case, error)); ok {
		return rf(ctx, caseCopy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Case) *models.Case); ok {
		r0 = rf(ctx, caseCopy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Case) error); ok {
		r1 = rf(ctx, caseCopy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCaseRepo creates a new instance of CaseRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCaseRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CaseRepo {
	mock := &CaseRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
