// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/sewaustav/CaseGoCore/internal/cases/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/sewaustav/CaseGoCore/internal/cases/models"
)

// CaseGoService is an autogenerated mock type for the CaseGoService type
type CaseGoService struct {
	mock.Mock
}

// CompleteDialogService provides a mock function with given fields: ctx, dialogID, user
func (_m *CaseGoService) CompleteDialogService(ctx context.Context, dialogID int64, user models.UserIdentity) (*dto.Result, error) {
	ret := _m.Called(ctx, dialogID, user)

	if len(ret) == 0 {
		panic("no return value specified for CompleteDialogService")
	}

	var r0 *dto.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) (*dto.Result, error)); ok {
		return rf(ctx, dialogID, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) *dto.Result); ok {
		r0 = rf(ctx, dialogID, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, models.UserIdentity) error); ok {
		r1 = rf(ctx, dialogID, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCaseService provides a mock function with given fields: ctx, caseDto, identity
func (_m *CaseGoService) CreateCaseService(ctx context.Context, caseDto *dto.NewCaseDto, identity models.UserIdentity) (*models.Case, error) {
	ret := _m.Called(ctx, caseDto, identity)

	if len(ret) == 0 {
		panic("no return value specified for CreateCaseService")
	}

	var r0 *models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.NewCaseDto, models.UserIdentity) (*models.Case, error)); ok {
		return rf(ctx, caseDto, identity)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.NewCaseDto, models.UserIdentity) *models.Case); ok {
		r0 = rf(ctx, caseDto, identity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.NewCaseDto, models.UserIdentity) error); ok {
		r1 = rf(ctx, caseDto, identity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCaseService provides a mock function with given fields: ctx, caseID, user
func (_m *CaseGoService) DeleteCaseService(ctx context.Context, caseID int64, user models.UserIdentity) error {
	ret := _m.Called(ctx, caseID, user)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCaseService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) error); ok {
		r0 = rf(ctx, caseID, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCaseByIDService provides a mock function with given fields: ctx, caseID
func (_m *CaseGoService) GetCaseByIDService(ctx context.Context, caseID int64) (*models.Case, error) {
	ret := _m.Called(ctx, caseID)

	if len(ret) == 0 {
		panic("no return value specified for GetCaseByIDService")
	}

	var r0 *models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Case, error)); ok {
		return rf(ctx, caseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Case); ok {
		r0 = rf(ctx, caseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, caseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCasesService provides a mock function with given fields: ctx, limit, page, settings
func (_m *CaseGoService) GetCasesService(ctx context.Context, limit int, page int, settings *dto.UserSettingsDto) ([]models.Case, error) {
	ret := _m.Called(ctx, limit, page, settings)

	if len(ret) == 0 {
		panic("no return value specified for GetCasesService")
	}

	var r0 []models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *dto.UserSettingsDto) ([]models.Case, error)); ok {
		return rf(ctx, limit, page, settings)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *dto.UserSettingsDto) []models.Case); ok {
		r0 = rf(ctx, limit, page, settings)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, *dto.UserSettingsDto) error); ok {
		r1 = rf(ctx, limit, page, settings)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserDialogByIDService provides a mock function with given fields: ctx, user, dialogID
func (_m *CaseGoService) GetUserDialogByIDService(ctx context.Context, user models.UserIdentity, dialogID int64) (*models.Conversation, error) {
	ret := _m.Called(ctx, user, dialogID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDialogByIDService")
	}

	var r0 *models.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64) (*models.Conversation, error)); ok {
		return rf(ctx, user, dialogID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64) *models.Conversation); ok {
		r0 = rf(ctx, user, dialogID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, int64) error); ok {
		r1 = rf(ctx, user, dialogID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersDialogsService provides a mock function with given fields: ctx, user, userID, limit, offset
func (_m *CaseGoService) GetUsersDialogsService(ctx context.Context, user models.UserIdentity, userID int64, limit int, offset int) ([]models.Conversation, error) {
	ret := _m.Called(ctx, user, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersDialogsService")
	}

	var r0 []models.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64, int, int) ([]models.Conversation, error)); ok {
		return rf(ctx, user, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64, int, int) []models.Conversation); ok {
		r0 = rf(ctx, user, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, int64, int, int) error); ok {
		r1 = rf(ctx, user, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleInteractionService provides a mock function with given fields: ctx, interaction, user
func (_m *CaseGoService) HandleInteractionService(ctx context.Context, interaction *dto.InteractionDto, user models.UserIdentity) (*dto.CaseDto, error) {
	ret := _m.Called(ctx, interaction, user)

	if len(ret) == 0 {
		panic("no return value specified for HandleInteractionService")
	}

	var r0 *dto.CaseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.InteractionDto, models.UserIdentity) (*dto.CaseDto, error)); ok {
		return rf(ctx, interaction, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.InteractionDto, models.UserIdentity) *dto.CaseDto); ok {
		r0 = rf(ctx, interaction, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CaseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.InteractionDto, models.UserIdentity) error); ok {
		r1 = rf(ctx, interaction, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchCaseService provides a mock function with given fields: ctx, caseID, caseDto, user
func (_m *CaseGoService) PatchCaseService(ctx context.Context, caseID int64, caseDto *dto.NewCaseDto, user models.UserIdentity) (*models.Case, error) {
	ret := _m.Called(ctx, caseID, caseDto, user)

	if len(ret) == 0 {
		panic("no return value specified for PatchCaseService")
	}

	var r0 *models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *dto.NewCaseDto, models.UserIdentity) (*models.Case, error)); ok {
		return rf(ctx, caseID, caseDto, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *dto.NewCaseDto, models.UserIdentity) *models.Case); ok {
		r0 = rf(ctx, caseID, caseDto, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *dto.NewCaseDto, models.UserIdentity) error); ok {
		r1 = rf(ctx, caseID, caseDto, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartDialogService provides a mock function with given fields: ctx, caseID, user
func (_m *CaseGoService) StartDialogService(ctx context.Context, caseID int64, user models.UserIdentity) (*models.Case, error) {
	ret := _m.Called(ctx, caseID, user)

	if len(ret) == 0 {
		panic("no return value specified for StartDialogService")
	}

	var r0 *models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) (*models.Case, error)); ok {
		return rf(ctx, caseID, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) *models.Case); ok {
		r0 = rf(ctx, caseID, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, models.UserIdentity) error); ok {
		r1 = rf(ctx, caseID, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCaseGoService creates a new instance of CaseGoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCaseGoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CaseGoService {
	mock := &CaseGoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
