// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/sewaustav/CaseGoCore/internal/cases/models"
	mock "github.com/stretchr/testify/mock"
)

// DialogRepo is an autogenerated mock type for the DialogRepo type
type DialogRepo struct {
	mock.Mock
}

// GetDialogByID provides a mock function with given fields: ctx, dialogID
func (_m *DialogRepo) GetDialogByID(ctx context.Context, dialogID int64) (*models.Dialog, error) {
	ret := _m.Called(ctx, dialogID)

	if len(ret) == 0 {
		panic("no return value specified for GetDialogByID")
	}

	var r0 *models.Dialog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Dialog, error)); ok {
		return rf(ctx, dialogID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Dialog); ok {
		r0 = rf(ctx, dialogID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Dialog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, dialogID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDialogsByCaseID provides a mock function with given fields: ctx, caseID, limit, offset
func (_m *DialogRepo) GetDialogsByCaseID(ctx context.Context, caseID int64, limit int, offset int) ([]models.Dialog, error) {
	ret := _m.Called(ctx, caseID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetDialogsByCaseID")
	}

	var r0 []models.Dialog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]models.Dialog, error)); ok {
		return rf(ctx, caseID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) []models.Dialog); ok {
		r0 = rf(ctx, caseID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Dialog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) error); ok {
		r1 = rf(ctx, caseID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserDialogs provides a mock function with given fields: ctx, userID, limit, offset
func (_m *DialogRepo) GetUserDialogs(ctx context.Context, userID int64, limit int, offset int) ([]models.Dialog, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDialogs")
	}

	var r0 []models.Dialog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]models.Dialog, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) []models.Dialog); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Dialog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartDialog provides a mock function with given fields: ctx, dialog
func (_m *DialogRepo) StartDialog(ctx context.Context, dialog *models.Dialog) (*models.Dialog, error) {
	ret := _m.Called(ctx, dialog)

	if len(ret) == 0 {
		panic("no return value specified for StartDialog")
	}

	var r0 *models.Dialog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Dialog) (*models.Dialog, error)); ok {
		return rf(ctx, dialog)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Dialog) *models.Dialog); ok {
		r0 = rf(ctx, dialog)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Dialog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Dialog) error); ok {
		r1 = rf(ctx, dialog)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountDialogs provides a mock function with given fields: ctx
func (_m *DialogRepo) CountDialogs(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountDialogs")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDialogRepo creates a new instance of DialogRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDialogRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *DialogRepo {
	mock := &DialogRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
