// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/sewaustav/CaseGoCore/internal/cases/models"
)

// GRPCService is an autogenerated mock type for the GRPCService type
type GRPCService struct {
	mock.Mock
}

// SendResults provides a mock function with given fields: ctx, msg
func (_m *GRPCService) SendResults(ctx context.Context, msg models.Result) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for SendResults")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Result) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGRPCService creates a new instance of GRPCService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGRPCService(t interface {
	mock.TestingT
	Cleanup(func())
}) *GRPCService {
	mock := &GRPCService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
