// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/sewaustav/CaseGoCore/internal/cases/models"
	mock "github.com/stretchr/testify/mock"
)

// Interactor is an autogenerated mock type for the Interactor type
type Interactor struct {
	mock.Mock
}

// Clear provides a mock function with given fields: ctx, dialogID
func (_m *Interactor) Clear(ctx context.Context, dialogID int64) error {
	ret := _m.Called(ctx, dialogID)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, dialogID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with no fields
func (_m *Interactor) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLast provides a mock function with given fields: ctx, dialogID
func (_m *Interactor) DeleteLast(ctx context.Context, dialogID int64) error {
	ret := _m.Called(ctx, dialogID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLast")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, dialogID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFullHistory provides a mock function with given fields: ctx, dialogID
func (_m *Interactor) GetFullHistory(ctx context.Context, dialogID int64) ([]models.Interaction, error) {
	ret := _m.Called(ctx, dialogID)

	if len(ret) == 0 {
		panic("no return value specified for GetFullHistory")
	}

	var r0 []models.Interaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.Interaction, error)); ok {
		return rf(ctx, dialogID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.Interaction); ok {
		r0 = rf(ctx, dialogID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Interaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, dialogID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Push provides a mock function with given fields: ctx, inter
func (_m *Interactor) Push(ctx context.Context, inter *models.Interaction) error {
	ret := _m.Called(ctx, inter)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Interaction) error); ok {
		r0 = rf(ctx, inter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewInteractor creates a new instance of Interactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInteractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Interactor {
	mock := &Interactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
