// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/sewaustav/CaseGoCore/internal/cases/models"
	mock "github.com/stretchr/testify/mock"

	repository "github.com/sewaustav/CaseGoCore/internal/cases/repository"
)

// Interaction is an autogenerated mock type for the Interaction type
type Interaction struct {
	mock.Mock
}

// Begin provides a mock function with given fields: ctx
func (_m *Interaction) Begin(ctx context.Context) (repository.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 repository.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInteractionByID provides a mock function with given fields: ctx, interactionID
func (_m *Interaction) GetInteractionByID(ctx context.Context, interactionID int64) (*models.Interaction, error) {
	ret := _m.Called(ctx, interactionID)

	if len(ret) == 0 {
		panic("no return value specified for GetInteractionByID")
	}

	var r0 *models.Interaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Interaction, error)); ok {
		return rf(ctx, interactionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Interaction); ok {
		r0 = rf(ctx, interactionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Interaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, interactionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInteractionsByDialogID provides a mock function with given fields: ctx, dialogID
func (_m *Interaction) GetInteractionsByDialogID(ctx context.Context, dialogID int64) ([]models.Interaction, error) {
	ret := _m.Called(ctx, dialogID)

	if len(ret) == 0 {
		panic("no return value specified for GetInteractionsByDialogID")
	}

	var r0 []models.Interaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.Interaction, error)); ok {
		return rf(ctx, dialogID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.Interaction); ok {
		r0 = rf(ctx, dialogID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Interaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, dialogID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutInteraction provides a mock function with given fields: ctx, interaction
func (_m *Interaction) PutInteraction(ctx context.Context, interaction *models.Interaction) error {
	ret := _m.Called(ctx, interaction)

	if len(ret) == 0 {
		panic("no return value specified for PutInteraction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Interaction) error); ok {
		r0 = rf(ctx, interaction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: tx
func (_m *Interaction) WithTx(tx repository.Tx) repository.Interaction {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.Interaction
	if rf, ok := ret.Get(0).(func(repository.Tx) repository.Interaction); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Interaction)
		}
	}

	return r0
}

// NewInteraction creates a new instance of Interaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInteraction(t interface {
	mock.TestingT
	Cleanup(func())
}) *Interaction {
	mock := &Interaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
