// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/sewaustav/CaseGoCore/internal/cases/dto"

	mock "github.com/stretchr/testify/mock"

	models "github.com/sewaustav/CaseGoCore/internal/cases/models"
)

// LevelGrpcClient is an autogenerated mock type for the LevelGrpcClient type
type LevelGrpcClient struct {
	mock.Mock
}

// LevelDoneGrpcHandler provides a mock function with given fields: ctx, user, req
func (_m *LevelGrpcClient) LevelDoneGrpcHandler(ctx context.Context, user models.UserIdentity, req *dto.LevelXpResult) (*dto.UserLevelInfo, error) {
	ret := _m.Called(ctx, user, req)

	if len(ret) == 0 {
		panic("no return value specified for LevelDoneGrpcHandler")
	}

	var r0 *dto.UserLevelInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, *dto.LevelXpResult) (*dto.UserLevelInfo, error)); ok {
		return rf(ctx, user, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, *dto.LevelXpResult) *dto.UserLevelInfo); ok {
		r0 = rf(ctx, user, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserLevelInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, *dto.LevelXpResult) error); ok {
		r1 = rf(ctx, user, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLevelGrpcClient creates a new instance of LevelGrpcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLevelGrpcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *LevelGrpcClient {
	mock := &LevelGrpcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
