// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/sewaustav/CaseGoCore/internal/cases/dto"

	mock "github.com/stretchr/testify/mock"

	models "github.com/sewaustav/CaseGoCore/internal/cases/models"
)

// LLM is an autogenerated mock type for the LLM type
type LLM struct {
	mock.Mock
}

// AnalyzeCase provides a mock function with given fields: ctx, conv
func (_m *LLM) AnalyzeCase(ctx context.Context, conv []models.Interaction) (*dto.Result, error) {
	ret := _m.Called(ctx, conv)

	if len(ret) == 0 {
		panic("no return value specified for AnalyzeCase")
	}

	var r0 *dto.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Interaction) (*dto.Result, error)); ok {
		return rf(ctx, conv)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.Interaction) *dto.Result); ok {
		r0 = rf(ctx, conv)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.Interaction) error); ok {
		r1 = rf(ctx, conv)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateCase provides a mock function with given fields: ctx, description
func (_m *LLM) GenerateCase(ctx context.Context, description string) (*models.Case, error) {
	ret := _m.Called(ctx, description)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCase")
	}

	var r0 *models.Case
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Case, error)); ok {
		return rf(ctx, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Case); ok {
		r0 = rf(ctx, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Case)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GenerateResponse provides a mock function with given fields: ctx, history
func (_m *LLM) GenerateResponse(ctx context.Context, history []models.Interaction) (*dto.CaseDto, error) {
	ret := _m.Called(ctx, history)

	if len(ret) == 0 {
		panic("no return value specified for GenerateResponse")
	}

	var r0 *dto.CaseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Interaction) (*dto.CaseDto, error)); ok {
		return rf(ctx, history)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.Interaction) *dto.CaseDto); ok {
		r0 = rf(ctx, history)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CaseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.Interaction) error); ok {
		r1 = rf(ctx, history)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLLM creates a new instance of LLM. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLLM(t interface {
	mock.TestingT
	Cleanup(func())
}) *LLM {
	mock := &LLM{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
