// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/sewaustav/CaseGoCore/internal/cases/dto"

	mock "github.com/stretchr/testify/mock"
)

// PaymentGrpcClient is an autogenerated mock type for the PaymentGrpcClient type
type PaymentGrpcClient struct {
	mock.Mock
}

// CheckStatus provides a mock function with given fields: ctx, userID
func (_m *PaymentGrpcClient) CheckStatus(ctx context.Context, userID int64) (*dto.SubscriptionStatusDto, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CheckStatus")
	}

	var r0 *dto.SubscriptionStatusDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*dto.SubscriptionStatusDto, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *dto.SubscriptionStatusDto); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SubscriptionStatusDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentGrpcClient creates a new instance of PaymentGrpcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentGrpcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentGrpcClient {
	mock := &PaymentGrpcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
