// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/sewaustav/CaseGoCore/internal/cases/dto"
	mock "github.com/stretchr/testify/mock"
)

// SubscriptionInfo is an autogenerated mock type for the SubscriptionInfo type
type SubscriptionInfo struct {
	mock.Mock
}

// GetSubInfo provides a mock function with given fields: ctx, userID
func (_m *SubscriptionInfo) GetSubInfo(ctx context.Context, userID int64) (*dto.SubscriptionStatusDto, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubInfo")
	}

	var r0 *dto.SubscriptionStatusDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*dto.SubscriptionStatusDto, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *dto.SubscriptionStatusDto); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SubscriptionStatusDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PushSubInfo provides a mock function with given fields: ctx, userID, sub
func (_m *SubscriptionInfo) PushSubInfo(ctx context.Context, userID int64, sub dto.SubscriptionStatusDto) error {
	ret := _m.Called(ctx, userID, sub)

	if len(ret) == 0 {
		panic("no return value specified for PushSubInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, dto.SubscriptionStatusDto) error); ok {
		r0 = rf(ctx, userID, sub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSubscriptionInfo creates a new instance of SubscriptionInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriptionInfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriptionInfo {
	mock := &SubscriptionInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
