// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/YoungFlores/Case_Go/Profile/internal/profile/models"
	mock "github.com/stretchr/testify/mock"
)

// LevelRepo is an autogenerated mock type for the LevelRepo type
type LevelRepo struct {
	mock.Mock
}

// CreateLevel provides a mock function with given fields: ctx, userLevel
func (_m *LevelRepo) CreateLevel(ctx context.Context, userLevel *models.UserLevel) (*models.UserLevel, error) {
	ret := _m.Called(ctx, userLevel)

	if len(ret) == 0 {
		panic("no return value specified for CreateLevel")
	}

	var r0 *models.UserLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserLevel) (*models.UserLevel, error)); ok {
		return rf(ctx, userLevel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserLevel) *models.UserLevel); ok {
		r0 = rf(ctx, userLevel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserLevel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UserLevel) error); ok {
		r1 = rf(ctx, userLevel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUserLevel provides a mock function with given fields: ctx, userID
func (_m *LevelRepo) DeleteUserLevel(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserLevel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserLevel provides a mock function with given fields: ctx, userID
func (_m *LevelRepo) GetUserLevel(ctx context.Context, userID int64) (*models.UserLevel, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserLevel")
	}

	var r0 *models.UserLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.UserLevel, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.UserLevel); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserLevel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLevel provides a mock function with given fields: ctx, userLevel
func (_m *LevelRepo) UpdateLevel(ctx context.Context, userLevel *models.UserLevel) (*models.UserLevel, error) {
	ret := _m.Called(ctx, userLevel)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLevel")
	}

	var r0 *models.UserLevel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserLevel) (*models.UserLevel, error)); ok {
		return rf(ctx, userLevel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserLevel) *models.UserLevel); ok {
		r0 = rf(ctx, userLevel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserLevel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UserLevel) error); ok {
		r1 = rf(ctx, userLevel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLevelRepo creates a new instance of LevelRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLevelRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *LevelRepo {
	mock := &LevelRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
