// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/YoungFlores/Case_Go/Profile/internal/profile/models"
	mock "github.com/stretchr/testify/mock"

	profiledto "github.com/YoungFlores/Case_Go/Profile/internal/profile/dto"

	profilerepo "github.com/YoungFlores/Case_Go/Profile/internal/profile/repository/profile_repo"
)

// ProfileRepo is an autogenerated mock type for the ProfileRepo type
type ProfileRepo struct {
	mock.Mock
}

// AddProfession provides a mock function with given fields: ctx, profession
func (_m *ProfileRepo) AddProfession(ctx context.Context, profession *models.UserProfession) (*models.UserProfession, error) {
	ret := _m.Called(ctx, profession)

	if len(ret) == 0 {
		panic("no return value specified for AddProfession")
	}

	var r0 *models.UserProfession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserProfession) (*models.UserProfession, error)); ok {
		return rf(ctx, profession)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserProfession) *models.UserProfession); ok {
		r0 = rf(ctx, profession)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserProfession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UserProfession) error); ok {
		r1 = rf(ctx, profession)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddPurposes provides a mock function with given fields: ctx, purposes
func (_m *ProfileRepo) AddPurposes(ctx context.Context, purposes []models.UserPurpose) ([]models.UserPurpose, error) {
	ret := _m.Called(ctx, purposes)

	if len(ret) == 0 {
		panic("no return value specified for AddPurposes")
	}

	var r0 []models.UserPurpose
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.UserPurpose) ([]models.UserPurpose, error)); ok {
		return rf(ctx, purposes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.UserPurpose) []models.UserPurpose); ok {
		r0 = rf(ctx, purposes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.UserPurpose) error); ok {
		r1 = rf(ctx, purposes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddSocial provides a mock function with given fields: ctx, links
func (_m *ProfileRepo) AddSocial(ctx context.Context, links []models.UserSocialLink) ([]models.UserSocialLink, error) {
	ret := _m.Called(ctx, links)

	if len(ret) == 0 {
		panic("no return value specified for AddSocial")
	}

	var r0 []models.UserSocialLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.UserSocialLink) ([]models.UserSocialLink, error)); ok {
		return rf(ctx, links)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.UserSocialLink) []models.UserSocialLink); ok {
		r0 = rf(ctx, links)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserSocialLink)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.UserSocialLink) error); ok {
		r1 = rf(ctx, links)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Begin provides a mock function with given fields: ctx
func (_m *ProfileRepo) Begin(ctx context.Context) (profilerepo.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 profilerepo.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (profilerepo.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) profilerepo.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(profilerepo.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateProfile provides a mock function with given fields: ctx, user
func (_m *ProfileRepo) CreateProfile(ctx context.Context, user *models.Profile) (*models.Profile, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfile")
	}

	var r0 *models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Profile) (*models.Profile, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Profile) *models.Profile); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Profile) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteProfession provides a mock function with given fields: ctx, professionID
func (_m *ProfileRepo) DeleteProfession(ctx context.Context, professionID int64) error {
	ret := _m.Called(ctx, professionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, professionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProfile provides a mock function with given fields: ctx, userID
func (_m *ProfileRepo) DeleteProfile(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProfileWithoutRecovery provides a mock function with given fields: ctx, userID
func (_m *ProfileRepo) DeleteProfileWithoutRecovery(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfileWithoutRecovery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePurpose provides a mock function with given fields: ctx, id
func (_m *ProfileRepo) DeletePurpose(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePurpose")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteSocial provides a mock function with given fields: ctx, id
func (_m *ProfileRepo) DeleteSocial(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSocial")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditProfession provides a mock function with given fields: ctx, profession
func (_m *ProfileRepo) EditProfession(ctx context.Context, profession *models.UserProfession) (*models.UserProfession, error) {
	ret := _m.Called(ctx, profession)

	if len(ret) == 0 {
		panic("no return value specified for EditProfession")
	}

	var r0 *models.UserProfession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserProfession) (*models.UserProfession, error)); ok {
		return rf(ctx, profession)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserProfession) *models.UserProfession); ok {
		r0 = rf(ctx, profession)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserProfession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UserProfession) error); ok {
		r1 = rf(ctx, profession)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EditPurpose provides a mock function with given fields: ctx, purpose
func (_m *ProfileRepo) EditPurpose(ctx context.Context, purpose *models.UserPurpose) ([]models.UserPurpose, error) {
	ret := _m.Called(ctx, purpose)

	if len(ret) == 0 {
		panic("no return value specified for EditPurpose")
	}

	var r0 []models.UserPurpose
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserPurpose) ([]models.UserPurpose, error)); ok {
		return rf(ctx, purpose)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserPurpose) []models.UserPurpose); ok {
		r0 = rf(ctx, purpose)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UserPurpose) error); ok {
		r1 = rf(ctx, purpose)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EditSocial provides a mock function with given fields: ctx, link
func (_m *ProfileRepo) EditSocial(ctx context.Context, link *models.UserSocialLink) ([]models.UserSocialLink, error) {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for EditSocial")
	}

	var r0 []models.UserSocialLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserSocialLink) ([]models.UserSocialLink, error)); ok {
		return rf(ctx, link)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.UserSocialLink) []models.UserSocialLink); ok {
		r0 = rf(ctx, link)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserSocialLink)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.UserSocialLink) error); ok {
		r1 = rf(ctx, link)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllProfessions provides a mock function with given fields: ctx, userID
func (_m *ProfileRepo) GetAllProfessions(ctx context.Context, userID int64) ([]models.UserProfession, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProfessions")
	}

	var r0 []models.UserProfession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.UserProfession, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.UserProfession); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserProfession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUsers provides a mock function with given fields: ctx, limit, offset
func (_m *ProfileRepo) GetAllUsers(ctx context.Context, limit int, offset int) ([]models.Profile, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]models.Profile, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []models.Profile); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfileByID provides a mock function with given fields: ctx, id
func (_m *ProfileRepo) GetProfileByID(ctx context.Context, id int64) (*models.Profile, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileByID")
	}

	var r0 *models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Profile, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Profile); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfileIDByProfessionID provides a mock function with given fields: ctx, professionID
func (_m *ProfileRepo) GetProfileIDByProfessionID(ctx context.Context, professionID int64) (int64, error) {
	ret := _m.Called(ctx, professionID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileIDByProfessionID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, professionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, professionID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, professionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByProfileID provides a mock function with given fields: ctx, id, userID
func (_m *ProfileRepo) GetUserByProfileID(ctx context.Context, id int64, userID int64) (int64, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByProfileID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (int64, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) int64); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserProfile provides a mock function with given fields: ctx, userID
func (_m *ProfileRepo) GetUserProfile(ctx context.Context, userID int64) (*models.Profile, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfile")
	}

	var r0 *models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Profile, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Profile); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPurposes provides a mock function with given fields: ctx, userID
func (_m *ProfileRepo) GetUserPurposes(ctx context.Context, userID int64) ([]models.UserPurpose, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPurposes")
	}

	var r0 []models.UserPurpose
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.UserPurpose, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.UserPurpose); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserSocials provides a mock function with given fields: ctx, userID
func (_m *ProfileRepo) GetUserSocials(ctx context.Context, userID int64) ([]models.UserSocialLink, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSocials")
	}

	var r0 []models.UserSocialLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]models.UserSocialLink, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []models.UserSocialLink); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserSocialLink)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchProfile provides a mock function with given fields: ctx, userID, updates
func (_m *ProfileRepo) PatchProfile(ctx context.Context, userID int64, updates profiledto.UpdateProfilePartialDTO) (*models.Profile, error) {
	ret := _m.Called(ctx, userID, updates)

	if len(ret) == 0 {
		panic("no return value specified for PatchProfile")
	}

	var r0 *models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, profiledto.UpdateProfilePartialDTO) (*models.Profile, error)); ok {
		return rf(ctx, userID, updates)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, profiledto.UpdateProfilePartialDTO) *models.Profile); ok {
		r0 = rf(ctx, userID, updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, profiledto.UpdateProfilePartialDTO) error); ok {
		r1 = rf(ctx, userID, updates)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateLinks provides a mock function with given fields: ctx, links
func (_m *ProfileRepo) UpdateLinks(ctx context.Context, links []models.UserSocialLink) ([]models.UserSocialLink, error) {
	ret := _m.Called(ctx, links)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLinks")
	}

	var r0 []models.UserSocialLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.UserSocialLink) ([]models.UserSocialLink, error)); ok {
		return rf(ctx, links)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.UserSocialLink) []models.UserSocialLink); ok {
		r0 = rf(ctx, links)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserSocialLink)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.UserSocialLink) error); ok {
		r1 = rf(ctx, links)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfile provides a mock function with given fields: ctx, user
func (_m *ProfileRepo) UpdateProfile(ctx context.Context, user *models.Profile) (*models.Profile, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Profile) (*models.Profile, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Profile) *models.Profile); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Profile) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePurposes provides a mock function with given fields: ctx, purposes
func (_m *ProfileRepo) UpdatePurposes(ctx context.Context, purposes []models.UserPurpose) ([]models.UserPurpose, error) {
	ret := _m.Called(ctx, purposes)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePurposes")
	}

	var r0 []models.UserPurpose
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.UserPurpose) ([]models.UserPurpose, error)); ok {
		return rf(ctx, purposes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.UserPurpose) []models.UserPurpose); ok {
		r0 = rf(ctx, purposes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.UserPurpose) error); ok {
		r1 = rf(ctx, purposes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithTx provides a mock function with given fields: tx
func (_m *ProfileRepo) WithTx(tx profilerepo.Tx) profilerepo.ProfileRepo {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 profilerepo.ProfileRepo
	if rf, ok := ret.Get(0).(func(profilerepo.Tx) profilerepo.ProfileRepo); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(profilerepo.ProfileRepo)
		}
	}

	return r0
}

// NewProfileRepo creates a new instance of ProfileRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileRepo {
	mock := &ProfileRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
