// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/YoungFlores/Case_Go/Profile/internal/profile/models"
	mock "github.com/stretchr/testify/mock"

	profiledto "github.com/YoungFlores/Case_Go/Profile/internal/profile/dto"
)

// ProfileCore is an autogenerated mock type for the ProfileCore type
type ProfileCore struct {
	mock.Mock
}

// AddProfessionService provides a mock function with given fields: ctx, usr, req
func (_m *ProfileCore) AddProfessionService(ctx context.Context, usr models.UserIdentity, req []profiledto.ProfessionDTO) ([]models.UserProfession, error) {
	ret := _m.Called(ctx, usr, req)

	if len(ret) == 0 {
		panic("no return value specified for AddProfessionService")
	}

	var r0 []models.UserProfession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, []profiledto.ProfessionDTO) ([]models.UserProfession, error)); ok {
		return rf(ctx, usr, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, []profiledto.ProfessionDTO) []models.UserProfession); ok {
		r0 = rf(ctx, usr, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserProfession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, []profiledto.ProfessionDTO) error); ok {
		r1 = rf(ctx, usr, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddPurposesService provides a mock function with given fields: ctx, req, usr
func (_m *ProfileCore) AddPurposesService(ctx context.Context, req []profiledto.UserPurposeDTO, usr models.UserIdentity) ([]models.UserPurpose, error) {
	ret := _m.Called(ctx, req, usr)

	if len(ret) == 0 {
		panic("no return value specified for AddPurposesService")
	}

	var r0 []models.UserPurpose
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []profiledto.UserPurposeDTO, models.UserIdentity) ([]models.UserPurpose, error)); ok {
		return rf(ctx, req, usr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []profiledto.UserPurposeDTO, models.UserIdentity) []models.UserPurpose); ok {
		r0 = rf(ctx, req, usr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []profiledto.UserPurposeDTO, models.UserIdentity) error); ok {
		r1 = rf(ctx, req, usr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddSocialLinksService provides a mock function with given fields: ctx, req, usr
func (_m *ProfileCore) AddSocialLinksService(ctx context.Context, req []profiledto.SocialLinkDTO, usr models.UserIdentity) ([]models.UserSocialLink, error) {
	ret := _m.Called(ctx, req, usr)

	if len(ret) == 0 {
		panic("no return value specified for AddSocialLinksService")
	}

	var r0 []models.UserSocialLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []profiledto.SocialLinkDTO, models.UserIdentity) ([]models.UserSocialLink, error)); ok {
		return rf(ctx, req, usr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []profiledto.SocialLinkDTO, models.UserIdentity) []models.UserSocialLink); ok {
		r0 = rf(ctx, req, usr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserSocialLink)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []profiledto.SocialLinkDTO, models.UserIdentity) error); ok {
		r1 = rf(ctx, req, usr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateProfileService provides a mock function with given fields: ctx, req, usr
func (_m *ProfileCore) CreateProfileService(ctx context.Context, req profiledto.CreateProfileRequest, usr models.UserIdentity) (*models.UserProfile, error) {
	ret := _m.Called(ctx, req, usr)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfileService")
	}

	var r0 *models.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, profiledto.CreateProfileRequest, models.UserIdentity) (*models.UserProfile, error)); ok {
		return rf(ctx, req, usr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, profiledto.CreateProfileRequest, models.UserIdentity) *models.UserProfile); ok {
		r0 = rf(ctx, req, usr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, profiledto.CreateProfileRequest, models.UserIdentity) error); ok {
		r1 = rf(ctx, req, usr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteLinkService provides a mock function with given fields: ctx, id, usr
func (_m *ProfileCore) DeleteLinkService(ctx context.Context, id int64, usr models.UserIdentity) error {
	ret := _m.Called(ctx, id, usr)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLinkService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) error); ok {
		r0 = rf(ctx, id, usr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProfessionService provides a mock function with given fields: ctx, id, usr
func (_m *ProfileCore) DeleteProfessionService(ctx context.Context, id int64, usr models.UserIdentity) error {
	ret := _m.Called(ctx, id, usr)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfessionService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) error); ok {
		r0 = rf(ctx, id, usr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProfileService provides a mock function with given fields: ctx, usr
func (_m *ProfileCore) DeleteProfileService(ctx context.Context, usr models.UserIdentity) error {
	ret := _m.Called(ctx, usr)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfileService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity) error); ok {
		r0 = rf(ctx, usr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProfileWithoutRecoveryService provides a mock function with given fields: ctx, usr, userID
func (_m *ProfileCore) DeleteProfileWithoutRecoveryService(ctx context.Context, usr models.UserIdentity, userID int64) error {
	ret := _m.Called(ctx, usr, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProfileWithoutRecoveryService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64) error); ok {
		r0 = rf(ctx, usr, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePurposeService provides a mock function with given fields: ctx, id, usr
func (_m *ProfileCore) DeletePurposeService(ctx context.Context, id int64, usr models.UserIdentity) error {
	ret := _m.Called(ctx, id, usr)

	if len(ret) == 0 {
		panic("no return value specified for DeletePurposeService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) error); ok {
		r0 = rf(ctx, id, usr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditProfessionCategoryService provides a mock function with given fields: ctx, usr, profession
func (_m *ProfileCore) EditProfessionCategoryService(ctx context.Context, usr models.UserIdentity, profession *models.UserProfession) (*models.UserProfession, error) {
	ret := _m.Called(ctx, usr, profession)

	if len(ret) == 0 {
		panic("no return value specified for EditProfessionCategoryService")
	}

	var r0 *models.UserProfession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, *models.UserProfession) (*models.UserProfession, error)); ok {
		return rf(ctx, usr, profession)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, *models.UserProfession) *models.UserProfession); ok {
		r0 = rf(ctx, usr, profession)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserProfession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, *models.UserProfession) error); ok {
		r1 = rf(ctx, usr, profession)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUsersService provides a mock function with given fields: ctx, usr, limit, page
func (_m *ProfileCore) GetAllUsersService(ctx context.Context, usr models.UserIdentity, limit int, page int) ([]models.Profile, error) {
	ret := _m.Called(ctx, usr, limit, page)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsersService")
	}

	var r0 []models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int, int) ([]models.Profile, error)); ok {
		return rf(ctx, usr, limit, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int, int) []models.Profile); ok {
		r0 = rf(ctx, usr, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, int, int) error); ok {
		r1 = rf(ctx, usr, limit, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfessionsService provides a mock function with given fields: ctx, usr
func (_m *ProfileCore) GetProfessionsService(ctx context.Context, usr models.UserIdentity) ([]models.UserProfession, error) {
	ret := _m.Called(ctx, usr)

	if len(ret) == 0 {
		panic("no return value specified for GetProfessionsService")
	}

	var r0 []models.UserProfession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity) ([]models.UserProfession, error)); ok {
		return rf(ctx, usr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity) []models.UserProfession); ok {
		r0 = rf(ctx, usr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserProfession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity) error); ok {
		r1 = rf(ctx, usr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserProfileByIDService provides a mock function with given fields: ctx, usr, id
func (_m *ProfileCore) GetUserProfileByIDService(ctx context.Context, usr models.UserIdentity, id int64) (*models.UserProfile, error) {
	ret := _m.Called(ctx, usr, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfileByIDService")
	}

	var r0 *models.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64) (*models.UserProfile, error)); ok {
		return rf(ctx, usr, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64) *models.UserProfile); ok {
		r0 = rf(ctx, usr, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, int64) error); ok {
		r1 = rf(ctx, usr, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserProfileService provides a mock function with given fields: ctx, usr
func (_m *ProfileCore) GetUserProfileService(ctx context.Context, usr models.UserIdentity) (*models.UserProfile, error) {
	ret := _m.Called(ctx, usr)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfileService")
	}

	var r0 *models.UserProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity) (*models.UserProfile, error)); ok {
		return rf(ctx, usr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity) *models.UserProfile); ok {
		r0 = rf(ctx, usr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity) error); ok {
		r1 = rf(ctx, usr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchProfileService provides a mock function with given fields: ctx, usr, req
func (_m *ProfileCore) PatchProfileService(ctx context.Context, usr models.UserIdentity, req profiledto.UpdateProfilePartialDTO) (*models.Profile, error) {
	ret := _m.Called(ctx, usr, req)

	if len(ret) == 0 {
		panic("no return value specified for PatchProfileService")
	}

	var r0 *models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, profiledto.UpdateProfilePartialDTO) (*models.Profile, error)); ok {
		return rf(ctx, usr, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, profiledto.UpdateProfilePartialDTO) *models.Profile); ok {
		r0 = rf(ctx, usr, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, profiledto.UpdateProfilePartialDTO) error); ok {
		r1 = rf(ctx, usr, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfileService provides a mock function with given fields: ctx, usr, req
func (_m *ProfileCore) UpdateProfileService(ctx context.Context, usr models.UserIdentity, req profiledto.ProfileInfoDTO) (*models.Profile, error) {
	ret := _m.Called(ctx, usr, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfileService")
	}

	var r0 *models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, profiledto.ProfileInfoDTO) (*models.Profile, error)); ok {
		return rf(ctx, usr, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, profiledto.ProfileInfoDTO) *models.Profile); ok {
		r0 = rf(ctx, usr, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, profiledto.ProfileInfoDTO) error); ok {
		r1 = rf(ctx, usr, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePurposeService provides a mock function with given fields: ctx, req, usr, id
func (_m *ProfileCore) UpdatePurposeService(ctx context.Context, req profiledto.UserPurposeDTO, usr models.UserIdentity, id int64) ([]models.UserPurpose, error) {
	ret := _m.Called(ctx, req, usr, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePurposeService")
	}

	var r0 []models.UserPurpose
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, profiledto.UserPurposeDTO, models.UserIdentity, int64) ([]models.UserPurpose, error)); ok {
		return rf(ctx, req, usr, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, profiledto.UserPurposeDTO, models.UserIdentity, int64) []models.UserPurpose); ok {
		r0 = rf(ctx, req, usr, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserPurpose)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, profiledto.UserPurposeDTO, models.UserIdentity, int64) error); ok {
		r1 = rf(ctx, req, usr, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSocialLinkService provides a mock function with given fields: ctx, req, usr, id
func (_m *ProfileCore) UpdateSocialLinkService(ctx context.Context, req profiledto.SocialLinkDTO, usr models.UserIdentity, id int64) ([]models.UserSocialLink, error) {
	ret := _m.Called(ctx, req, usr, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSocialLinkService")
	}

	var r0 []models.UserSocialLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, profiledto.SocialLinkDTO, models.UserIdentity, int64) ([]models.UserSocialLink, error)); ok {
		return rf(ctx, req, usr, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, profiledto.SocialLinkDTO, models.UserIdentity, int64) []models.UserSocialLink); ok {
		r0 = rf(ctx, req, usr, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.UserSocialLink)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, profiledto.SocialLinkDTO, models.UserIdentity, int64) error); ok {
		r1 = rf(ctx, req, usr, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProfileCore creates a new instance of ProfileCore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileCore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileCore {
	mock := &ProfileCore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
