// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/YoungFlores/Case_Go/Profile/internal/search/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/YoungFlores/Case_Go/Profile/internal/profile/models"
)

// SearchServiceInterface is an autogenerated mock type for the SearchServiceInterface type
type SearchServiceInterface struct {
	mock.Mock
}

// SearchByFioService provides a mock function with given fields: ctx, req, helpers
func (_m *SearchServiceInterface) SearchByFioService(ctx context.Context, req dto.SearchByFIODTO, helpers dto.SearchHelpersDTO) ([]models.Profile, error) {
	ret := _m.Called(ctx, req, helpers)

	if len(ret) == 0 {
		panic("no return value specified for SearchByFioService")
	}

	var r0 []models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.SearchByFIODTO, dto.SearchHelpersDTO) ([]models.Profile, error)); ok {
		return rf(ctx, req, helpers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.SearchByFIODTO, dto.SearchHelpersDTO) []models.Profile); ok {
		r0 = rf(ctx, req, helpers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.SearchByFIODTO, dto.SearchHelpersDTO) error); ok {
		r1 = rf(ctx, req, helpers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchProfileService provides a mock function with given fields: ctx, req, helpers
func (_m *SearchServiceInterface) SearchProfileService(ctx context.Context, req dto.SearchDTO, helpers dto.SearchHelpersDTO) ([]models.Profile, error) {
	ret := _m.Called(ctx, req, helpers)

	if len(ret) == 0 {
		panic("no return value specified for SearchProfileService")
	}

	var r0 []models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.SearchDTO, dto.SearchHelpersDTO) ([]models.Profile, error)); ok {
		return rf(ctx, req, helpers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.SearchDTO, dto.SearchHelpersDTO) []models.Profile); ok {
		r0 = rf(ctx, req, helpers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.SearchDTO, dto.SearchHelpersDTO) error); ok {
		r1 = rf(ctx, req, helpers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSearchServiceInterface creates a new instance of SearchServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearchServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchServiceInterface {
	mock := &SearchServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
