// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/YoungFlores/Case_Go/Profile/internal/search/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/YoungFlores/Case_Go/Profile/internal/profile/models"
)

// SearchRepo is an autogenerated mock type for the SearchRepo type
type SearchRepo struct {
	mock.Mock
}

// SearchByFio provides a mock function with given fields: ctx, req, limit, offset
func (_m *SearchRepo) SearchByFio(ctx context.Context, req dto.SearchByFIODTO, limit uint64, offset uint64) ([]models.Profile, error) {
	ret := _m.Called(ctx, req, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchByFio")
	}

	var r0 []models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.SearchByFIODTO, uint64, uint64) ([]models.Profile, error)); ok {
		return rf(ctx, req, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.SearchByFIODTO, uint64, uint64) []models.Profile); ok {
		r0 = rf(ctx, req, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.SearchByFIODTO, uint64, uint64) error); ok {
		r1 = rf(ctx, req, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchProfile provides a mock function with given fields: ctx, req, limit, offset, sortBy, sortOrder
func (_m *SearchRepo) SearchProfile(ctx context.Context, req dto.SearchDTO, limit uint64, offset uint64, sortBy string, sortOrder string) ([]models.Profile, error) {
	ret := _m.Called(ctx, req, limit, offset, sortBy, sortOrder)

	if len(ret) == 0 {
		panic("no return value specified for SearchProfile")
	}

	var r0 []models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.SearchDTO, uint64, uint64, string, string) ([]models.Profile, error)); ok {
		return rf(ctx, req, limit, offset, sortBy, sortOrder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.SearchDTO, uint64, uint64, string, string) []models.Profile); ok {
		r0 = rf(ctx, req, limit, offset, sortBy, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Profile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.SearchDTO, uint64, uint64, string, string) error); ok {
		r1 = rf(ctx, req, limit, offset, sortBy, sortOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSearchRepo creates a new instance of SearchRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearchRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchRepo {
	mock := &SearchRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
