// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/sewaustav/Payment/internal/payment/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/sewaustav/Payment/internal/payment/models"
)

// PaymentApiService is an autogenerated mock type for the PaymentApiService type
type PaymentApiService struct {
	mock.Mock
}

// DeleteUserService provides a mock function with given fields: ctx, usr, userID
func (_m *PaymentApiService) DeleteUserService(ctx context.Context, usr models.UserIdentity, userID int64) error {
	ret := _m.Called(ctx, usr, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64) error); ok {
		r0 = rf(ctx, usr, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMyPaymentsService provides a mock function with given fields: ctx, usr, limit, page
func (_m *PaymentApiService) GetMyPaymentsService(ctx context.Context, usr models.UserIdentity, limit int, page int) ([]models.PaymentInfo, error) {
	ret := _m.Called(ctx, usr, limit, page)

	if len(ret) == 0 {
		panic("no return value specified for GetMyPaymentsService")
	}

	var r0 []models.PaymentInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int, int) ([]models.PaymentInfo, error)); ok {
		return rf(ctx, usr, limit, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int, int) []models.PaymentInfo); ok {
		r0 = rf(ctx, usr, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PaymentInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, int, int) error); ok {
		r1 = rf(ctx, usr, limit, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentByIDService provides a mock function with given fields: ctx, usr, id
func (_m *PaymentApiService) GetPaymentByIDService(ctx context.Context, usr models.UserIdentity, id int64) (*models.PaymentInfo, error) {
	ret := _m.Called(ctx, usr, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByIDService")
	}

	var r0 *models.PaymentInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64) (*models.PaymentInfo, error)); ok {
		return rf(ctx, usr, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64) *models.PaymentInfo); ok {
		r0 = rf(ctx, usr, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaymentInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, int64) error); ok {
		r1 = rf(ctx, usr, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentByTransactionIDService provides a mock function with given fields: ctx, usr, id
func (_m *PaymentApiService) GetPaymentByTransactionIDService(ctx context.Context, usr models.UserIdentity, id string) (*models.PaymentInfo, error) {
	ret := _m.Called(ctx, usr, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByTransactionIDService")
	}

	var r0 *models.PaymentInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, string) (*models.PaymentInfo, error)); ok {
		return rf(ctx, usr, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, string) *models.PaymentInfo); ok {
		r0 = rf(ctx, usr, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaymentInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, string) error); ok {
		r1 = rf(ctx, usr, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStatusService provides a mock function with given fields: ctx, usr
func (_m *PaymentApiService) GetStatusService(ctx context.Context, usr models.UserIdentity) (*dto.SubscriptionStatusDto, error) {
	ret := _m.Called(ctx, usr)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusService")
	}

	var r0 *dto.SubscriptionStatusDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity) (*dto.SubscriptionStatusDto, error)); ok {
		return rf(ctx, usr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity) *dto.SubscriptionStatusDto); ok {
		r0 = rf(ctx, usr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.SubscriptionStatusDto)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity) error); ok {
		r1 = rf(ctx, usr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubscriptionInfoService provides a mock function with given fields: ctx, usr
func (_m *PaymentApiService) GetSubscriptionInfoService(ctx context.Context, usr models.UserIdentity) (*models.SubscriptionInfo, error) {
	ret := _m.Called(ctx, usr)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionInfoService")
	}

	var r0 *models.SubscriptionInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity) (*models.SubscriptionInfo, error)); ok {
		return rf(ctx, usr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity) *models.SubscriptionInfo); ok {
		r0 = rf(ctx, usr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SubscriptionInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity) error); ok {
		r1 = rf(ctx, usr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserProfileService provides a mock function with given fields: ctx, usr, userID
func (_m *PaymentApiService) GetUserProfileService(ctx context.Context, usr models.UserIdentity, userID int64) (*models.SubscriptionInfo, error) {
	ret := _m.Called(ctx, usr, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfileService")
	}

	var r0 *models.SubscriptionInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64) (*models.SubscriptionInfo, error)); ok {
		return rf(ctx, usr, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64) *models.SubscriptionInfo); ok {
		r0 = rf(ctx, usr, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SubscriptionInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, int64) error); ok {
		r1 = rf(ctx, usr, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsersPaymentsService provides a mock function with given fields: ctx, usr, userID, limit, page
func (_m *PaymentApiService) GetUsersPaymentsService(ctx context.Context, usr models.UserIdentity, userID int64, limit int, page int) ([]models.PaymentInfo, error) {
	ret := _m.Called(ctx, usr, userID, limit, page)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersPaymentsService")
	}

	var r0 []models.PaymentInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64, int, int) ([]models.PaymentInfo, error)); ok {
		return rf(ctx, usr, userID, limit, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64, int, int) []models.PaymentInfo); ok {
		r0 = rf(ctx, usr, userID, limit, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PaymentInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, int64, int, int) error); ok {
		r1 = rf(ctx, usr, userID, limit, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GiftSubscription provides a mock function with given fields: ctx, usr, userID
func (_m *PaymentApiService) GiftSubscription(ctx context.Context, usr models.UserIdentity, userID int64) error {
	ret := _m.Called(ctx, usr, userID)

	if len(ret) == 0 {
		panic("no return value specified for GiftSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, int64) error); ok {
		r0 = rf(ctx, usr, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterUserService provides a mock function with given fields: ctx, usr
func (_m *PaymentApiService) RegisterUserService(ctx context.Context, usr models.UserIdentity) error {
	ret := _m.Called(ctx, usr)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUserService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity) error); ok {
		r0 = rf(ctx, usr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateSubscriptionInfoService provides a mock function with given fields: ctx, usr, sub
func (_m *PaymentApiService) UpdateSubscriptionInfoService(ctx context.Context, usr models.UserIdentity, sub dto.UpdateSubscriptionInfoDto) error {
	ret := _m.Called(ctx, usr, sub)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubscriptionInfoService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, dto.UpdateSubscriptionInfoDto) error); ok {
		r0 = rf(ctx, usr, sub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentApiService creates a new instance of PaymentApiService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentApiService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentApiService {
	mock := &PaymentApiService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
