// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/sewaustav/Payment/internal/payment/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/sewaustav/Payment/internal/payment/models"

	repository "github.com/sewaustav/Payment/internal/payment/repository"
)

// PaymentRepo is an autogenerated mock type for the PaymentRepo type
type PaymentRepo struct {
	mock.Mock
}

// Begin provides a mock function with given fields: ctx
func (_m *PaymentRepo) Begin(ctx context.Context) (repository.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 repository.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (repository.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) repository.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreatePayment provides a mock function with given fields: ctx, payment
func (_m *PaymentRepo) CreatePayment(ctx context.Context, payment *models.PaymentInfo) (*models.PaymentInfo, error) {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 *models.PaymentInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PaymentInfo) (*models.PaymentInfo, error)); ok {
		return rf(ctx, payment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.PaymentInfo) *models.PaymentInfo); ok {
		r0 = rf(ctx, payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaymentInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.PaymentInfo) error); ok {
		r1 = rf(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: ctx, userID
func (_m *PaymentRepo) DeleteUser(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPaymentByID provides a mock function with given fields: ctx, id
func (_m *PaymentRepo) GetPaymentByID(ctx context.Context, id int64) (*models.PaymentInfo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByID")
	}

	var r0 *models.PaymentInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.PaymentInfo, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.PaymentInfo); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaymentInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentByTransactionID provides a mock function with given fields: ctx, id
func (_m *PaymentRepo) GetPaymentByTransactionID(ctx context.Context, id string) (*models.PaymentInfo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByTransactionID")
	}

	var r0 *models.PaymentInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PaymentInfo, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PaymentInfo); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaymentInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubscriptionStatus provides a mock function with given fields: ctx, userID
func (_m *PaymentRepo) GetSubscriptionStatus(ctx context.Context, userID int64) (dto.SubscriptionStatusDto, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionStatus")
	}

	var r0 dto.SubscriptionStatusDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (dto.SubscriptionStatusDto, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) dto.SubscriptionStatusDto); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(dto.SubscriptionStatusDto)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPayments provides a mock function with given fields: ctx, userID, limit, offset
func (_m *PaymentRepo) GetUserPayments(ctx context.Context, userID int64, limit int, offset int) ([]models.PaymentInfo, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPayments")
	}

	var r0 []models.PaymentInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]models.PaymentInfo, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) []models.PaymentInfo); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PaymentInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserSubscriptionInfo provides a mock function with given fields: ctx, userID
func (_m *PaymentRepo) GetUserSubscriptionInfo(ctx context.Context, userID int64) (*models.SubscriptionInfo, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSubscriptionInfo")
	}

	var r0 *models.SubscriptionInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.SubscriptionInfo, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.SubscriptionInfo); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SubscriptionInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitSubscription provides a mock function with given fields: ctx, sub
func (_m *PaymentRepo) InitSubscription(ctx context.Context, sub *models.SubscriptionInfo) (*models.SubscriptionInfo, error) {
	ret := _m.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for InitSubscription")
	}

	var r0 *models.SubscriptionInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.SubscriptionInfo) (*models.SubscriptionInfo, error)); ok {
		return rf(ctx, sub)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.SubscriptionInfo) *models.SubscriptionInfo); ok {
		r0 = rf(ctx, sub)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SubscriptionInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.SubscriptionInfo) error); ok {
		r1 = rf(ctx, sub)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSubscription provides a mock function with given fields: ctx, userID, sub
func (_m *PaymentRepo) UpdateSubscription(ctx context.Context, userID int64, sub *dto.UpdateSubscriptionInfoDto) error {
	ret := _m.Called(ctx, userID, sub)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *dto.UpdateSubscriptionInfoDto) error); ok {
		r0 = rf(ctx, userID, sub)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithTx provides a mock function with given fields: tx
func (_m *PaymentRepo) WithTx(tx repository.Tx) repository.PaymentRepo {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 repository.PaymentRepo
	if rf, ok := ret.Get(0).(func(repository.Tx) repository.PaymentRepo); ok {
		r0 = rf(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repository.PaymentRepo)
		}
	}

	return r0
}

// NewPaymentRepo creates a new instance of PaymentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRepo {
	mock := &PaymentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
