// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AnalyticsRepo is an autogenerated mock type for the AnalyticsRepo type
type AnalyticsRepo struct {
	mock.Mock
}

// NewAnalyticsRepo creates a new instance of AnalyticsRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsRepo {
	mock := &AnalyticsRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
