// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/sewaustav/CaseGoProfile/internal/case_profile/models"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// CaseResultRepo is an autogenerated mock type for the CaseResultRepo type
type CaseResultRepo struct {
	mock.Mock
}

// AddResult provides a mock function with given fields: ctx, result
func (_m *CaseResultRepo) AddResult(ctx context.Context, result *models.CaseResult) error {
	ret := _m.Called(ctx, result)

	if len(ret) == 0 {
		panic("no return value specified for AddResult")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CaseResult) error); ok {
		r0 = rf(ctx, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteResultByID provides a mock function with given fields: ctx, id
func (_m *CaseResultRepo) DeleteResultByID(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResultByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetHistoryBy provides a mock function with given fields: ctx, userID, from
func (_m *CaseResultRepo) GetHistoryBy(ctx context.Context, userID int64, from time.Time) ([]*models.CaseProfileHistory, error) {
	ret := _m.Called(ctx, userID, from)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoryBy")
	}

	var r0 []*models.CaseProfileHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time) ([]*models.CaseProfileHistory, error)); ok {
		return rf(ctx, userID, from)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time) []*models.CaseProfileHistory); ok {
		r0 = rf(ctx, userID, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.CaseProfileHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, time.Time) error); ok {
		r1 = rf(ctx, userID, from)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfileByID provides a mock function with given fields: ctx, id
func (_m *CaseResultRepo) GetProfileByID(ctx context.Context, id int64) (*models.CaseProfile, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileByID")
	}

	var r0 *models.CaseProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.CaseProfile, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.CaseProfile); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CaseProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfileByUserID provides a mock function with given fields: ctx, userID
func (_m *CaseResultRepo) GetProfileByUserID(ctx context.Context, userID int64) (*models.CaseProfile, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileByUserID")
	}

	var r0 *models.CaseProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.CaseProfile, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.CaseProfile); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CaseProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetResultByDialogID provides a mock function with given fields: ctx, dialogID
func (_m *CaseResultRepo) GetResultByDialogID(ctx context.Context, dialogID int64) (*models.CaseResult, error) {
	ret := _m.Called(ctx, dialogID)

	if len(ret) == 0 {
		panic("no return value specified for GetResultByDialogID")
	}

	var r0 *models.CaseResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.CaseResult, error)); ok {
		return rf(ctx, dialogID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.CaseResult); ok {
		r0 = rf(ctx, dialogID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CaseResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, dialogID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreProfile provides a mock function with given fields: ctx, result
func (_m *CaseResultRepo) StoreProfile(ctx context.Context, result *models.CaseProfile) error {
	ret := _m.Called(ctx, result)

	if len(ret) == 0 {
		panic("no return value specified for StoreProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CaseProfile) error); ok {
		r0 = rf(ctx, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProfile provides a mock function with given fields: ctx, result
func (_m *CaseResultRepo) UpdateProfile(ctx context.Context, result *models.CaseProfile) error {
	ret := _m.Called(ctx, result)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.CaseProfile) error); ok {
		r0 = rf(ctx, result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCaseResultRepo creates a new instance of CaseResultRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCaseResultRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CaseResultRepo {
	mock := &CaseResultRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
