// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/sewaustav/CaseGoProfile/internal/case_profile/dto"
	mock "github.com/stretchr/testify/mock"

	models "github.com/sewaustav/CaseGoProfile/internal/case_profile/models"

	time "time"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// DeleteResultByIDService provides a mock function with given fields: ctx, id, user
func (_m *Service) DeleteResultByIDService(ctx context.Context, id int64, user models.UserIdentity) error {
	ret := _m.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResultByIDService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) error); ok {
		r0 = rf(ctx, id, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetHistoryService provides a mock function with given fields: ctx, user, from
func (_m *Service) GetHistoryService(ctx context.Context, user models.UserIdentity, from time.Time) ([]*models.CaseProfileHistory, error) {
	ret := _m.Called(ctx, user, from)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoryService")
	}

	var r0 []*models.CaseProfileHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, time.Time) ([]*models.CaseProfileHistory, error)); ok {
		return rf(ctx, user, from)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity, time.Time) []*models.CaseProfileHistory); ok {
		r0 = rf(ctx, user, from)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.CaseProfileHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity, time.Time) error); ok {
		r1 = rf(ctx, user, from)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfileByIDService provides a mock function with given fields: ctx, id, user
func (_m *Service) GetProfileByIDService(ctx context.Context, id int64, user models.UserIdentity) (*models.CaseProfile, error) {
	ret := _m.Called(ctx, id, user)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileByIDService")
	}

	var r0 *models.CaseProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) (*models.CaseProfile, error)); ok {
		return rf(ctx, id, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) *models.CaseProfile); ok {
		r0 = rf(ctx, id, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CaseProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, models.UserIdentity) error); ok {
		r1 = rf(ctx, id, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfileByUserIDService provides a mock function with given fields: ctx, userID, user
func (_m *Service) GetProfileByUserIDService(ctx context.Context, userID int64, user models.UserIdentity) (*models.CaseProfile, error) {
	ret := _m.Called(ctx, userID, user)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileByUserIDService")
	}

	var r0 *models.CaseProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) (*models.CaseProfile, error)); ok {
		return rf(ctx, userID, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) *models.CaseProfile); ok {
		r0 = rf(ctx, userID, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CaseProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, models.UserIdentity) error); ok {
		r1 = rf(ctx, userID, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProfileService provides a mock function with given fields: ctx, user
func (_m *Service) GetProfileService(ctx context.Context, user models.UserIdentity) (*models.CaseProfile, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileService")
	}

	var r0 *models.CaseProfile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity) (*models.CaseProfile, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserIdentity) *models.CaseProfile); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CaseProfile)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserIdentity) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserHistoryService provides a mock function with given fields: ctx, userID, user
func (_m *Service) GetUserHistoryService(ctx context.Context, userID int64, user models.UserIdentity) ([]*models.CaseProfileHistory, error) {
	ret := _m.Called(ctx, userID, user)

	if len(ret) == 0 {
		panic("no return value specified for GetUserHistoryService")
	}

	var r0 []*models.CaseProfileHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) ([]*models.CaseProfileHistory, error)); ok {
		return rf(ctx, userID, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, models.UserIdentity) []*models.CaseProfileHistory); ok {
		r0 = rf(ctx, userID, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.CaseProfileHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, models.UserIdentity) error); ok {
		r1 = rf(ctx, userID, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleResultsService provides a mock function with given fields: ctx, result, user
func (_m *Service) HandleResultsService(ctx context.Context, result dto.Result, user models.UserIdentity) error {
	ret := _m.Called(ctx, result, user)

	if len(ret) == 0 {
		panic("no return value specified for HandleResultsService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.Result, models.UserIdentity) error); ok {
		r0 = rf(ctx, result, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
