// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/categories": {
            "get": {
                "description": "Возвращает полный список категорий профессий",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profession-category"
                ],
                "summary": "Получить все категории",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profession_categories_models.CategoryDTO"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создает новую категорию (только для админов)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profession-category"
                ],
                "summary": "Создать категорию профессий",
                "parameters": [
                    {
                        "description": "Данные категории",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profession_categories_models.CategoryDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profession_categories_models.CategoryDTO"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/categories/parent/{parentID}": {
            "get": {
                "description": "Возвращает список категорий, привязанных к конкретному родителю",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profession-category"
                ],
                "summary": "Получить подкатегории по ParentID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Parent ID",
                        "name": "parentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profession_categories_models.CategoryDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid parentID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/categories/{id}": {
            "get": {
                "description": "Возвращает одну категорию по её уникальному идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profession-category"
                ],
                "summary": "Получить категорию по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profession_categories_models.CategoryDTO"
                        }
                    },
                    "400": {
                        "description": "Invalid id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Получить свой профиль",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_models.Profile"
                        }
                    },
                    "204": {
                        "description": "Профиль не активен"
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Полное обновление профиля",
                "parameters": [
                    {
                        "description": "Новые данные профиля",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.ProfileInfoDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_models.Profile"
                        }
                    },
                    "409": {
                        "description": "Conflict - Field already taken",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создает профиль пользователя с соцсетями и целями",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Создать новый профиль",
                "parameters": [
                    {
                        "description": "Данные профиля",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.CreateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Профиль успешно создан",
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_models.Profile"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict - Field already taken",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Мягкое удаление своего профиля",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Частично обновить профиль",
                "parameters": [
                    {
                        "description": "Поля для обновления",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.UpdateProfilePartialDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_models.Profile"
                        }
                    }
                }
            }
        },
        "/profile/purpose/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "purpose"
                ],
                "summary": "Удалить цель",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID цели",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                }
            }
        },
        "/profile/purposes": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purpose"
                ],
                "summary": "Создать новые цели",
                "parameters": [
                    {
                        "description": "Список целей",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.UserPurposeDTO"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.UserPurposeDTO"
                            }
                        }
                    }
                }
            }
        },
        "/profile/social": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "social"
                ],
                "summary": "Добавить ссылки на соцсети",
                "parameters": [
                    {
                        "description": "Список ссылок",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.SocialLinkDTO"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.SocialLinkDTO"
                            }
                        }
                    }
                }
            }
        },
        "/profile/social/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "social"
                ],
                "summary": "Обновить конкретную соц. ссылку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID ссылки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные ссылки",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.SocialLinkDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.SocialLinkDTO"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Not your link",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "social"
                ],
                "summary": "Удалить соц. ссылку",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID ссылки",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                }
            }
        },
        "/profile/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Позволяет просмотреть чужой профиль по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Получить профиль по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID профиля",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_models.Profile"
                        }
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Полное удаление профиля (Admin only)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                }
            }
        },
        "/profiles/purpose/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "purpose"
                ],
                "summary": "Обновить конкретную цель",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID цели",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Данные цели",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.UserPurposeDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.UserPurposeDTO"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Фильтрация профилей по профессии, возрасту, городу и полу",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Поиск профилей по фильтрам",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID профессии",
                        "name": "profession_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Название профессии",
                        "name": "profession",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Мин. возраст",
                        "name": "min_age",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Макс. возраст",
                        "name": "max_age",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Город",
                        "name": "city",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Пол (0 или 1)",
                        "name": "sex",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Лимит",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Страница",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_models.Profile"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid search params",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/search/fio": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Поиск по имени, фамилии или отчеству",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Поиск профилей по ФИО",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Имя",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Фамилия",
                        "name": "surname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Отчество",
                        "name": "patronymic",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Лимит",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Страница",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_models.Profile"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_YoungFlores_Case_Go_Profile_internal_profession_categories_models.CategoryDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.CreateProfileRequest": {
            "type": "object",
            "required": [
                "info",
                "purposes"
            ],
            "properties": {
                "info": {
                    "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.ProfileInfoDTO"
                },
                "purposes": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.UserPurposeDTO"
                    }
                },
                "social_links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.SocialLinkDTO"
                    }
                }
            }
        },
        "github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.ProfileInfoDTO": {
            "type": "object",
            "required": [
                "avatar",
                "name",
                "surname",
                "username"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "maximum": 120,
                    "minimum": 14
                },
                "avatar": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "name": {
                    "type": "string"
                },
                "patronymic": {
                    "type": "string"
                },
                "profession": {
                    "type": "string"
                },
                "sex": {
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                },
                "surname": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 3
                }
            }
        },
        "github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.SocialLinkDTO": {
            "type": "object",
            "required": [
                "type",
                "url"
            ],
            "properties": {
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.UpdateProfilePartialDTO": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "maximum": 120,
                    "minimum": 14
                },
                "avatar": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "name": {
                    "type": "string"
                },
                "patronymic": {
                    "type": "string"
                },
                "profession": {
                    "type": "string"
                },
                "sex": {
                    "type": "integer",
                    "enum": [
                        0,
                        1
                    ]
                },
                "surname": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 30,
                    "minLength": 3
                }
            }
        },
        "github_com_YoungFlores_Case_Go_Profile_internal_profile_dto.UserPurposeDTO": {
            "type": "object",
            "required": [
                "purpose"
            ],
            "properties": {
                "purpose": {
                    "type": "string",
                    "minLength": 5
                }
            }
        },
        "github_com_YoungFlores_Case_Go_Profile_internal_profile_models.Profile": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer"
                },
                "avatar": {
                    "type": "string"
                },
                "case_count": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "patronymic": {
                    "type": "string"
                },
                "profession": {
                    "type": "string"
                },
                "sex": {
                    "$ref": "#/definitions/github_com_YoungFlores_Case_Go_Profile_internal_profile_models.UserSex"
                },
                "surname": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_YoungFlores_Case_Go_Profile_internal_profile_models.UserSex": {
            "type": "integer",
            "enum": [
                0,
                1
            ],
            "x-enum-varnames": [
                "Male",
                "Female"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/profile/api/v1",
	Schemes:          []string{},
	Title:            "Profile Service API",
	Description:      "API сервис для управления профилями пользователей.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
